AllCops:
  TargetRubyVersion: 2.4
  Exclude: ['spec/**/*']
Metrics/LineLength:
  IgnoredPatterns: ['raise', 'puts', '#', '@', 'spec']
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
